import { THEMES,THEME_IDS } from './themes';
import type { EnemyAttack,EnemyKind,MonsterRank,MonsterRole,StatusEffect,SupportAbility,ThemeId } from './types';

export interface MonsterProfile{id:string;name:string;kind:EnemyKind;attack:EnemyAttack;hp:number;damage:number;speed:number;tint:number;artId?:string;legacyFrame?:number;rank:MonsterRank;role:MonsterRole;onHit?:StatusEffect;support?:SupportAbility;dropChance:number;xpMultiplier:number}
export interface BossProfile extends MonsterProfile{bossIndex:number;abilities:EnemyAttack[];stationary?:boolean}
export const MONSTER_ART_IDS=['black-ogre','blue-demon','boar-fiend','bull-demon','burrowing-spider','burrowing-worm','cave-salamander-static','crawling-zombie','dual-blade-demon','elite-demon','elite-giant-stinkbug','elite-minotaur','elite-skeleton','fire-spider','ghost-samurai','giant-centipede','giant-cobra','giant-rat','giant-scorpion','giant-spider','giant-stinkbug','giant-venom-wasp','gray-minotaur','green-flying-insect','green-grub','hell-crab','hell-lord','lesser-minotaur','lesser-skeleton','lizard-fiend','minotaur-captain','minotaur-fire-mage','minotaur-gladiator','minotaur-ice-mage','minotaur-warrior','mutant-carnivorous-plant-static','mutant-maggot','ogre','ogre-chieftain','puppet','red-demon','red-ogre','skeleton','skeleton-archer','skeleton-assassin','skeleton-captain','skeleton-guardian','skeleton-lord','skeleton-spearman','skeleton-warrior','spider-archer','spiked-beetle','swift-spider','werewolf-villager-1','werewolf-villager-2','wolf','worm-snake','yeti','zombie-1','zombie-2'] as const;
export type MonsterArtId=typeof MONSTER_ART_IDS[number];
export const RANK_DROP_CHANCE={normal:.018,elite:.32,superElite:.85,boss:1} as const;
const NAMES:Record<MonsterArtId,string>={'black-ogre':'黑巨怪','blue-demon':'蓝恶魔','boar-fiend':'獠牙猪怪','bull-demon':'牛魔','burrowing-spider':'遁地蜘蛛','burrowing-worm':'遁地虫','cave-salamander-static':'洞穴蝾螈','crawling-zombie':'爬行丧尸','dual-blade-demon':'双刀恶魔','elite-demon':'精英恶魔','elite-giant-stinkbug':'腐壳虫王','elite-minotaur':'精英牛头人','elite-skeleton':'精英骷髅','fire-spider':'火蜘蛛','ghost-samurai':'鬼武士','giant-centipede':'巨型蜈蚣','giant-cobra':'巨型眼镜蛇','giant-rat':'疫病大鼠','giant-scorpion':'巨型蝎子','giant-spider':'巨型蜘蛛','giant-stinkbug':'巨型臭虫','giant-venom-wasp':'巨毒蜂','gray-minotaur':'灰牛头人','green-flying-insect':'绿飞虫','green-grub':'绿腐虫','hell-crab':'地狱螃蟹','hell-lord':'地狱领主','lesser-minotaur':'低级牛头人','lesser-skeleton':'低等骷髅','lizard-fiend':'蜥蜴怪','minotaur-captain':'牛头队长','minotaur-fire-mage':'牛头火法师','minotaur-gladiator':'牛头斗士','minotaur-ice-mage':'牛头冰法师','minotaur-warrior':'牛头战士','mutant-carnivorous-plant-static':'变异食人花','mutant-maggot':'变异蛆','ogre':'巨怪','ogre-chieftain':'巨怪首领','puppet':'诅咒傀儡','red-demon':'红恶魔','red-ogre':'红巨怪','skeleton':'骷髅兵','skeleton-archer':'骷髅射手','skeleton-assassin':'骷髅杀手','skeleton-captain':'骷髅队长','skeleton-guardian':'骷髅守卫','skeleton-lord':'骷髅领主','skeleton-spearman':'骷髅长枪兵','skeleton-warrior':'骷髅战士','spider-archer':'蛛网射手','spiked-beetle':'尖刺甲虫','swift-spider':'高速蜘蛛','werewolf-villager-1':'狼人村民','werewolf-villager-2':'狂化狼人','wolf':'野狼','worm-snake':'蚯蚓蛇','yeti':'雪怪','zombie-1':'腐尸','zombie-2':'疫尸'};
const SUPER=new Set<MonsterArtId>(['hell-lord','skeleton-lord','ogre-chieftain','minotaur-captain','elite-demon','elite-minotaur','elite-skeleton','ghost-samurai']);
const ELITE=new Set<MonsterArtId>(['black-ogre','red-ogre','bull-demon','elite-giant-stinkbug','skeleton-captain','skeleton-guardian','minotaur-gladiator','gray-minotaur','giant-cobra','yeti','dual-blade-demon']);
const SUPPORT:Partial<Record<MonsterArtId,SupportAbility>>={'minotaur-ice-mage':'shield','minotaur-fire-mage':'teleport','skeleton-lord':'revive','skeleton-captain':'surround','elite-giant-stinkbug':'heal','hell-lord':'teleport','puppet':'shield','ghost-samurai':'teleport'};
const BASE:Record<EnemyKind,[number,number,number]>={skeleton:[52,11,55],zombie:[88,15,36],archer:[48,13,42],knight:[145,20,43],cultist:[64,17,38],wraith:[58,16,67],brute:[185,24,31],shaman:[72,14,37],stalker:[70,18,75],spitter:[61,15,40],guardian:[850,28,35],boss:[5200,34,28]};
function define(artId:MonsterArtId):MonsterProfile{
 const ranged=/archer|mage|flying|wasp|cobra|plant|salamander/.test(artId),poison=/venom|cobra|scorpion|stinkbug|grub|maggot|worm|salamander|plant/.test(artId),fast=/spider|wolf|assassin|samurai|dual-blade/.test(artId),large=/ogre|minotaur|bull-demon|yeti|guardian|lord/.test(artId);
 const kind:EnemyKind=/zombie/.test(artId)?'zombie':/skeleton-archer|spider-archer/.test(artId)?'archer':/mage/.test(artId)?'shaman':/puppet|samurai/.test(artId)?'wraith':large?'brute':fast?'stalker':poison?'spitter':/skeleton/.test(artId)?'skeleton':ranged?'archer':'knight';
 const attack:EnemyAttack=/fire-mage/.test(artId)?'meteor':/ice-mage/.test(artId)?'beam':poison?'poison':ranged?'shot':fast?'leap':large?'charge':'melee';
 const rank:MonsterRank=SUPER.has(artId)?'superElite':ELITE.has(artId)?'elite':'normal',role:MonsterRole=SUPPORT[artId]?'support':ranged?'ranged':fast?'ambusher':large?'tank':'frontline';
 const onHit:StatusEffect|undefined=poison?'poison':/spider/.test(artId)?'chill':/assassin|dual-blade|wolf/.test(artId)?'bleed':/ice/.test(artId)?'chill':/fire|red-demon|hell/.test(artId)?'burn':large?'stun':undefined;
 const [hp,damage,speed]=BASE[kind],scale=rank==='superElite'?2.4:rank==='elite'?1.55:1;
 return{id:artId,name:NAMES[artId],kind,attack,hp:hp*scale,damage:damage*(rank==='superElite'?1.35:rank==='elite'?1.16:1),speed:artId.endsWith('-static')?8:speed,tint:0xffffff,artId,rank,role,onHit,support:SUPPORT[artId],dropChance:RANK_DROP_CHANCE[rank],xpMultiplier:rank==='superElite'?4:rank==='elite'?2:1};
}
export const MONSTER_DEFINITIONS=Object.fromEntries(MONSTER_ART_IDS.map(id=>[id,define(id)])) as Record<MonsterArtId,MonsterProfile>;
export const THEME_ROSTERS:Record<ThemeId,MonsterArtId[]>={
 cave:['giant-rat','giant-spider','burrowing-spider','burrowing-worm','cave-salamander-static','mutant-maggot','green-grub','giant-centipede','giant-scorpion','spiked-beetle'],dungeon:['lesser-skeleton','skeleton','skeleton-archer','skeleton-spearman','skeleton-warrior','skeleton-assassin','skeleton-captain','skeleton-guardian','puppet','crawling-zombie'],cathedral:['skeleton','skeleton-archer','skeleton-guardian','skeleton-lord','puppet','ghost-samurai','elite-skeleton','zombie-1','red-demon','blue-demon'],abandonedVillage:['zombie-1','zombie-2','crawling-zombie','werewolf-villager-1','werewolf-villager-2','giant-rat','wolf','boar-fiend','mutant-carnivorous-plant-static','puppet'],inferno:['red-demon','blue-demon','elite-demon','hell-lord','hell-crab','fire-spider','black-ogre','red-ogre','bull-demon','lizard-fiend'],mountain:['yeti','wolf','boar-fiend','ogre','ogre-chieftain','gray-minotaur','lesser-minotaur','minotaur-warrior','giant-venom-wasp','elite-minotaur'],town:['zombie-1','zombie-2','crawling-zombie','werewolf-villager-1','werewolf-villager-2','giant-rat','wolf','puppet','mutant-maggot','skeleton-assassin'],palace:['skeleton-warrior','skeleton-captain','skeleton-guardian','skeleton-lord','ghost-samurai','elite-skeleton','dual-blade-demon','minotaur-captain','red-demon','puppet'],catacomb:['lesser-skeleton','skeleton','skeleton-archer','skeleton-spearman','skeleton-warrior','skeleton-assassin','skeleton-captain','skeleton-guardian','skeleton-lord','elite-skeleton'],sewer:['swift-spider','giant-stinkbug','elite-giant-stinkbug','green-flying-insect','green-grub','mutant-maggot','giant-centipede','burrowing-worm','worm-snake','crawling-zombie'],frozenRuins:['yeti','wolf','gray-minotaur','minotaur-ice-mage','skeleton-warrior','skeleton-archer','ghost-samurai','blue-demon','giant-spider','boar-fiend'],swamp:['giant-cobra','giant-scorpion','spider-archer','giant-venom-wasp','green-flying-insect','green-grub','mutant-carnivorous-plant-static','cave-salamander-static','worm-snake','giant-spider'],mine:['burrowing-spider','burrowing-worm','spiked-beetle','giant-centipede','giant-stinkbug','ogre','black-ogre','lesser-minotaur','minotaur-warrior','minotaur-gladiator'],desertTemple:['giant-cobra','giant-scorpion','spiked-beetle','worm-snake','lizard-fiend','lesser-minotaur','minotaur-warrior','minotaur-fire-mage','minotaur-captain','bull-demon'],abyssFortress:['red-demon','blue-demon','elite-demon','hell-lord','dual-blade-demon','fire-spider','hell-crab','bull-demon','red-ogre','ghost-samurai']};
export const THEME_MONSTERS=Object.fromEntries(THEME_IDS.map(theme=>[theme,THEME_ROSTERS[theme].map(id=>({...MONSTER_DEFINITIONS[id],id:`${theme}:${id}`,tint:THEMES[theme].accent}))])) as Record<ThemeId,MonsterProfile[]>;
const boss=(id:string,name:string,attack:EnemyAttack,abilities:EnemyAttack[],bossIndex:number,stationary=false,onHit?:StatusEffect):BossProfile=>({id,name,kind:'guardian',attack,abilities,hp:900+bossIndex*95,damage:26+bossIndex*2.4,speed:stationary?0:30+bossIndex,tint:0xffffff,bossIndex,artId:`common/${id}`,rank:'boss',role:stationary?'support':'tank',onHit,stationary,dropChance:1,xpMultiplier:12});
const COMMON_BOSSES:BossProfile[]=[
 boss('earth-mother-static','大地之母','nova',['nova','summon','jail'],0,true,'stun'),boss('hell-broodmother-static','地狱主虫','poison',['poison','summon','nova'],1,true,'poison'),boss('demon-king','恶魔之王','charge',['charge','meteor','nova'],2,false,'burn'),
 boss('ancient-tree-static','亵渎巨树','jail',['jail','summon','poison'],3,true,'poison'),boss('infernal-overlord','炼狱魔王','meteor',['meteor','beam','nova'],4,false,'burn'),boss('nightmare-serpent','梦魇魔蛇','poison',['poison','charge','jail'],5,false,'poison'),
 boss('flesh-mountain-static','腐肉山峦','nova',['nova','summon','poison'],6,true,'bleed'),boss('true-fire-dragon-static','真火龙','meteor',['meteor','beam','nova'],7,true,'burn'),boss('spider-king','蜘蛛之王','summon',['summon','jail','leap'],8,false,'chill'),
];
const THEME_BOSS_ORDER:Record<ThemeId,number[]>={cave:[8,5,1,3,0],dungeon:[2,6,3,8,5],cathedral:[2,4,6,3,0],abandonedVillage:[8,3,6,5,0],inferno:[4,7,2,1,6],mountain:[0,5,2,3,7],town:[6,8,3,2,5],palace:[2,4,7,0,6],catacomb:[3,6,8,5,1],sewer:[1,8,5,6,3],frozenRuins:[5,0,3,8,2],swamp:[8,5,1,3,0],mine:[0,6,3,2,1],desertTemple:[5,7,2,0,1],abyssFortress:[4,7,2,6,1]};
export const THEME_BOSSES=Object.fromEntries(THEME_IDS.map(theme=>[theme,THEME_BOSS_ORDER[theme].map(index=>({...COMMON_BOSSES[index],id:`${theme}:${COMMON_BOSSES[index].id}`,tint:THEMES[theme].accent}))])) as Record<ThemeId,BossProfile[]>;
export const FINAL_BOSSES:BossProfile[]=[{id:'dark-sovereign',name:'黑暗统治者',kind:'boss',attack:'beam',abilities:['beam','jail','meteor','summon','nova'],hp:5600,damage:42,speed:34,tint:0xffffff,bossIndex:0,artId:'final/dark-sovereign',rank:'boss',role:'support',support:'teleport',onHit:'curse',dropChance:1,xpMultiplier:25}];
