import type {Room,ThemeId} from './types';

export type LayoutPattern='organic'|'block'|'cruciform'|'ruined'|'fractured'|'ridge'|'streets'|'symmetric'|'crypt'|'channels'|'frost'|'islands'|'shafts'|'stepped'|'angular';
export type FloorMotif='rings'|'chains'|'cross'|'hearth'|'runes'|'strata'|'lanes'|'crown'|'bones'|'drains'|'snowflake'|'reeds'|'rails'|'sun'|'sigil';
export type ThemeHazard='rockfall'|'prisoners'|'bells'|'ambush'|'eruption'|'avalanche'|'plague'|'royalGuard'|'resurrection'|'toxicFlush'|'blizzard'|'bogGas'|'caveIn'|'sandstorm'|'abyssRift';
export interface ThemeDesign{
  layout:LayoutPattern;motif:FloorMotif;hazard:ThemeHazard;hazardName:string;
  roomNames:Record<Room['type'],string[]>;archetypes:Record<Room['type'],string[]>;
  secretName:string;secretArchetype:string;
  formations:Array<{name:string;units:number[]}>;
}

export const THEME_RELICS:Record<ThemeId,readonly [string,string]>={
  cave:['回声晶核','盲蛛女王之牙'],dungeon:['典狱长的断钥','无罪者铁枷'],cathedral:['殉道者圣徽','无声唱诗冠'],abandonedVillage:['最后一盏家灯','狼疫村契'],inferno:['不灭狱心','焚世君王角'],mountain:['断脊峰印','雪葬猎王披风'],town:['封城执政印','疫医最后的药箱'],palace:['灰冠残片','末代禁卫誓剑'],catacomb:['无名王子指骨','王陵守夜灯'],sewer:['毒潮阀芯','腐壳母巢囊'],frozenRuins:['永冬星核','霜王碎冕'],swamp:['女巫泥心','沉船引魂灯'],mine:['黑铁母矿','塌方者鸣镐'],desertTemple:['葬日金盘','法老蝎尾印'],abyssFortress:['深渊军令','裂隙凝视之眼']
};

/**
 * Indices in formations reference each theme's explicit ten-monster roster.
 * Keeping encounter composition beside room art direction makes a theme reviewable
 * as one unit while bestiary stats and authored sprite IDs remain centralized.
 */
export const THEME_DESIGNS:Record<ThemeId,ThemeDesign>={
  cave:{layout:'organic',motif:'rings',hazard:'rockfall',hazardName:'回声落石',roomNames:{entry:['潮湿裂口'],crypt:['菌丝洞室','兽骨巢穴'],altar:['回声石窟'],treasury:['晶簇空腔'],sanctum:['地底母巢']},archetypes:{entry:['cave-mouth'],crypt:['fungal-den','bone-nest'],altar:['echo-grotto'],treasury:['crystal-vault'],sanctum:['deep-lair']},secretName:'封闭晶洞',secretArchetype:'sealed-geode',formations:[{name:'蛛鼠群',units:[1,0,5]},{name:'甲虫楔阵',units:[9,7,6]},{name:'伏地猎群',units:[2,3,8]}]},
  dungeon:{layout:'block',motif:'chains',hazard:'prisoners',hazardName:'牢门暴动',roomNames:{entry:['锈锁门厅'],crypt:['囚犯牢房','刑具室'],altar:['狱卒岗哨'],treasury:['没收品仓库'],sanctum:['典狱深牢']},archetypes:{entry:['gatehouse'],crypt:['cells','torture-room'],altar:['watch-post'],treasury:['evidence-vault'],sanctum:['warden-hall']},secretName:'遗忘禁闭室',secretArchetype:'oubliette',formations:[{name:'盾矛狱阵',units:[7,3,1]},{name:'死囚突击',units:[5,4,0]},{name:'傀儡看守',units:[8,6,2]}]},
  cathedral:{layout:'cruciform',motif:'cross',hazard:'bells',hazardName:'丧钟召集',roomNames:{entry:['沉没前厅'],crypt:['侧翼礼拜堂','遗骨安置室'],altar:['染血耳堂'],treasury:['失落圣物室'],sanctum:['无声唱诗席']},archetypes:{entry:['narthex'],crypt:['chapel','ossuary'],altar:['transept'],treasury:['reliquary'],sanctum:['choir']},secretName:'封印忏悔室',secretArchetype:'sealed-confessional',formations:[{name:'圣卫盾线',units:[2,0,1]},{name:'亡魂送葬列',units:[4,0,5]},{name:'寒歌唱诗班',units:[0,1,9]}]},
  abandonedVillage:{layout:'ruined',motif:'hearth',hazard:'ambush',hazardName:'屋舍伏击',roomNames:{entry:['倒塌村口'],crypt:['焚毁民居','废弃畜栏'],altar:['枯井广场'],treasury:['封死酒窖'],sanctum:['村长宅邸']},archetypes:{entry:['village-gate'],crypt:['burned-home','abandoned-pen'],altar:['dry-well'],treasury:['sealed-cellar'],sanctum:['reeve-house']},secretName:'幸存者地窖',secretArchetype:'survivor-cellar',formations:[{name:'疫尸邻里',units:[0,1,5]},{name:'狼人狩猎队',units:[3,4,6]},{name:'荒园伏击',units:[8,7,9]}]},
  inferno:{layout:'fractured',motif:'runes',hazard:'eruption',hazardName:'炼狱喷发',roomNames:{entry:['焦骨裂隙'],crypt:['熔岩刑场','恶魔兵营'],altar:['献火祭台'],treasury:['狱火宝库'],sanctum:['焚世王座']},archetypes:{entry:['charred-rift'],crypt:['lava-pit','demon-barracks'],altar:['pyre-altar'],treasury:['hell-vault'],sanctum:['burning-throne']},secretName:'熄灭的火库',secretArchetype:'cold-ember-vault',formations:[{name:'恶魔双翼',units:[0,1,4]},{name:'地狱重阵',units:[3,6,7]},{name:'火蛛猎群',units:[5,2,9]}]},
  mountain:{layout:'ridge',motif:'strata',hazard:'avalanche',hazardName:'断脊雪崩',roomNames:{entry:['风蚀山口'],crypt:['猎人营盘','断桥平台'],altar:['先祖石阵'],treasury:['冻封辎重'],sanctum:['峰顶祭场']},archetypes:{entry:['mountain-pass'],crypt:['hunter-camp','broken-bridge'],altar:['ancestor-stones'],treasury:['frozen-cache'],sanctum:['summit-ring']},secretName:'隐蔽鹰巢',secretArchetype:'hidden-eyrie',formations:[{name:'狼群包抄',units:[1,1,2]},{name:'巨怪前锋',units:[3,4,8]},{name:'牛头山卫',units:[5,6,7]}]},
  town:{layout:'streets',motif:'lanes',hazard:'plague',hazardName:'疫雾漫街',roomNames:{entry:['幸存者路障'],crypt:['染疫街区','废弃工坊'],altar:['绞刑广场'],treasury:['封锁商会'],sanctum:['钟楼市厅']},archetypes:{entry:['barricade'],crypt:['plague-block','abandoned-workshop'],altar:['gallows-square'],treasury:['guild-store'],sanctum:['clock-hall']},secretName:'走私者暗仓',secretArchetype:'smuggler-cache',formations:[{name:'尸群漫街',units:[0,1,2]},{name:'狼人巷战',units:[3,4,6]},{name:'暗巷猎杀',units:[7,9,5]}]},
  palace:{layout:'symmetric',motif:'crown',hazard:'royalGuard',hazardName:'王庭增援',roomNames:{entry:['灰冠门廊'],crypt:['侍卫厅','镜像回廊'],altar:['觐见前庭'],treasury:['皇家珍藏室'],sanctum:['破碎王座厅']},archetypes:{entry:['royal-portico'],crypt:['guard-hall','mirror-gallery'],altar:['audience-court'],treasury:['royal-treasury'],sanctum:['broken-throne']},secretName:'密诏档案室',secretArchetype:'sealed-archive',formations:[{name:'王庭盾阵',units:[2,0,1]},{name:'禁卫处刑队',units:[3,6,4]},{name:'恶魔廷臣',units:[8,9,5]}]},
  catacomb:{layout:'crypt',motif:'bones',hazard:'resurrection',hazardName:'墓群复苏',roomNames:{entry:['送葬阶梯'],crypt:['棺椁长廊','遗骨壁龛'],altar:['守墓祭室'],treasury:['陪葬宝库'],sanctum:['王室墓宫']},archetypes:{entry:['funeral-stairs'],crypt:['coffin-gallery','bone-niches'],altar:['keeper-chapel'],treasury:['grave-goods'],sanctum:['royal-tomb']},secretName:'无名王子墓',secretArchetype:'nameless-tomb',formations:[{name:'盾矛亡军',units:[7,3,1]},{name:'墓道追猎',units:[5,4,0]},{name:'领主送葬队',units:[8,6,2]}]},
  sewer:{layout:'channels',motif:'drains',hazard:'toxicFlush',hazardName:'毒潮冲刷',roomNames:{entry:['排污闸口'],crypt:['沉淀池','虫巢管室'],altar:['阀门中枢'],treasury:['赃物暗渠'],sanctum:['主排水池']},archetypes:{entry:['sluice-gate'],crypt:['settling-basin','brood-pipe'],altar:['valve-hub'],treasury:['contraband-drain'],sanctum:['main-reservoir']},secretName:'干涸维护井',secretArchetype:'dry-maintenance-well',formations:[{name:'飞虫毒群',units:[4,5,6]},{name:'臭虫壁垒',units:[1,2,0]},{name:'管道伏击',units:[3,7,8]}]},
  frozenRuins:{layout:'frost',motif:'snowflake',hazard:'blizzard',hazardName:'霜封白灾',roomNames:{entry:['覆雪断门'],crypt:['冰棺庭院','冻裂兵舍'],altar:['寒星祭坛'],treasury:['霜锁宝库'],sanctum:['永冬王庭']},archetypes:{entry:['snow-gate'],crypt:['ice-coffin-court','frozen-barracks'],altar:['cold-star-altar'],treasury:['frost-vault'],sanctum:['winter-court']},secretName:'融冰密室',secretArchetype:'thawing-chamber',formations:[{name:'雪狼追猎',units:[1,1,9]},{name:'冰法盾群',units:[2,3,4]},{name:'寒魂突袭',units:[6,7,5]}]},
  swamp:{layout:'islands',motif:'reeds',hazard:'bogGas',hazardName:'沼气喷涌',roomNames:{entry:['腐木栈桥'],crypt:['沉尸泥潭','毒蕈孤岛'],altar:['女巫石环'],treasury:['沉船货舱'],sanctum:['哀嚎泥心']},archetypes:{entry:['rotted-boardwalk'],crypt:['corpse-mire','toadstool-isle'],altar:['witch-stones'],treasury:['sunken-hold'],sanctum:['wailing-heart']},secretName:'芦苇隐洲',secretArchetype:'reed-hidden-isle',formations:[{name:'毒蛇猎圈',units:[0,1,8]},{name:'飞虫毒幕',units:[3,4,5]},{name:'蛛网花巢',units:[2,6,9]}]},
  mine:{layout:'shafts',motif:'rails',hazard:'caveIn',hazardName:'矿井塌方',roomNames:{entry:['废弃升降台'],crypt:['采掘掌子面','矿工宿营'],altar:['爆破仓'],treasury:['矿脉库房'],sanctum:['黑铁主井']},archetypes:{entry:['abandoned-lift'],crypt:['working-face','miner-camp'],altar:['powder-store'],treasury:['ore-vault'],sanctum:['black-iron-shaft']},secretName:'富矿夹层',secretArchetype:'rich-vein',formations:[{name:'钻地虫群',units:[0,1,3]},{name:'甲虫矿壁',units:[2,4,5]},{name:'牛头监工队',units:[7,8,9]}]},
  desertTemple:{layout:'stepped',motif:'sun',hazard:'sandstorm',hazardName:'墓沙风暴',roomNames:{entry:['埋沙门塔'],crypt:['蝎蛇墓廊','守像厅'],altar:['日轮祭庭'],treasury:['法老贡库'],sanctum:['沙葬圣殿']},archetypes:{entry:['buried-pylon'],crypt:['serpent-gallery','statue-hall'],altar:['sun-court'],treasury:['pharaoh-vault'],sanctum:['sand-sanctum']},secretName:'盗墓者裂隙',secretArchetype:'tomb-robber-breach',formations:[{name:'蝎蛇围猎',units:[0,1,3]},{name:'神殿盾军',units:[5,6,8]},{name:'火法献祭队',units:[7,9,2]}]},
  abyssFortress:{layout:'angular',motif:'sigil',hazard:'abyssRift',hazardName:'深渊裂隙',roomNames:{entry:['虚空桥头'],crypt:['恶魔军械厅','折跃兵站'],altar:['渎神符阵'],treasury:['灵魂军库'],sanctum:['深渊指挥殿']},archetypes:{entry:['void-bridge'],crypt:['demon-armory','warp-barracks'],altar:['blasphemy-sigil'],treasury:['soul-arsenal'],sanctum:['abyss-command']},secretName:'封闭献魂间',secretArchetype:'sealed-soul-cell',formations:[{name:'恶魔战楔',units:[0,1,4]},{name:'领主突击队',units:[3,2,8]},{name:'鬼武折跃队',units:[9,7,6]}]},
};

export function roomIdentity(theme:ThemeId,type:Room['type'],index:number):{name:string;archetype:string}{
  const design=THEME_DESIGNS[theme],names=design.roomNames[type],archetypes=design.archetypes[type],choice=Math.floor(Math.abs(index)/4)%Math.max(names.length,archetypes.length);
  return{name:names[choice%names.length],archetype:archetypes[choice%archetypes.length]};
}
