"""Generate the typed runtime manifest for normalized effect sequences."""
from collections import Counter
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "public" / "assets" / "effects"
OUTPUT = ROOT / "src" / "render" / "effectManifest.ts"

records = []
for folder in sorted(p for p in ASSETS.rglob("*") if p.is_dir() and list(p.glob("*.png"))):
    counts = Counter()
    frame_numbers = {}
    for file in folder.glob("*.png"):
        pieces = file.stem.split("_")
        if len(pieces) == 3:
            key = (int(pieces[0]), pieces[1])
            counts[key] += 1
            frame_numbers.setdefault(key, []).append(int(pieces[2]))
    if not counts:
        continue
    action = "stand" if any(key[1] == "stand" for key in counts) else sorted(counts)[0][1]
    directions = sorted(key[0] for key in counts if key[1] == action)
    start = min(frame_numbers[(directions[0], action)])
    first = folder / f"{directions[0]}_{action}_{start}.png"
    width, height = Image.open(first).size
    records.append((str(folder.relative_to(ASSETS)).replace("\\", "/"), action, start,
                    counts[(directions[0], action)], len(directions), width, height))

lines = [
    "// Generated by scripts/build_effect_manifest.py. Do not hand-edit frame counts.",
    "export interface EffectAssetMeta{path:string;action:string;start:number;frames:number;directions:1|8;width:number;height:number}",
    "export const EFFECT_MANIFEST={",
]
for path, action, start, frames, directions, width, height in records:
    lines.append(f"  '{path}':{{path:'{path}',action:'{action}',start:{start},frames:{frames},directions:{directions},width:{width},height:{height}}},")
lines += ["} as const satisfies Record<string,EffectAssetMeta>;", "export type EffectAssetId=keyof typeof EFFECT_MANIFEST;", ""]
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(records)} effect sequences to {OUTPUT.relative_to(ROOT)}")
