"""Generate runtime metadata for authored, separate-frame sprite folders.

The script reads PNG dimensions and alpha bounds only. It never rewrites source art.
Run it after adding or replacing a character, monster, NPC, or wing folder.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "public" / "assets"
OUTPUT = ROOT / "src" / "render" / "spriteManifest.ts"
PATTERN = re.compile(r"^(\d+)_(attack|death|hit|run|skill|stand)_(\d+)\.png$", re.I)
CATEGORIES = {
    "character": ASSETS / "characters",
    "monster": ASSETS / "monsters",
    "npc": ASSETS / "npc",
    "wing": ASSETS / "wings",
    "boss": ASSETS / "bosses",
}


def folder_metadata(folder: Path) -> dict:
    files = []
    frames: dict[str, dict[str, int]] = {}
    for file in folder.glob("*.png"):
        match = PATTERN.match(file.name)
        if not match:
            continue
        direction, action, frame = match.groups()
        files.append(file)
        action_frames = frames.setdefault(action.lower(), {})
        action_frames[direction] = max(action_frames.get(direction, 0), int(frame) + 1)
    if not files:
        return {}

    anchor_file = folder / "4_stand_0.png"
    if not anchor_file.exists():
        anchor_file = files[0]
    with Image.open(anchor_file) as image:
        width, height = image.size
        alpha = image.getchannel("A")
        bounds = alpha.getbbox() or (0, 0, width, height)
    left, top, right, bottom = bounds
    return {
        "width": width,
        "height": height,
        "originX": round(((left + right) / 2) / width, 5),
        "originY": round(bottom / height, 5),
        "visibleHeight": bottom - top,
        "frames": frames,
    }


manifest: dict[str, dict] = {}
for category, root in CATEGORIES.items():
    folders = sorted((folder for folder in root.rglob("*") if folder.is_dir()), key=lambda folder: str(folder)) if category == "boss" else sorted(root.iterdir())
    for folder in folders:
        if not folder.is_dir() or (category != "boss" and folder.name == "common"):
            continue
        metadata = folder_metadata(folder)
        if metadata:
            asset_id = folder.relative_to(root).as_posix() if category == "boss" else folder.name
            manifest[f"{category}:{asset_id}"] = metadata

body = json.dumps(manifest, ensure_ascii=False, indent=2)
OUTPUT.write_text(
    "// Generated by scripts/generate-sprite-manifest.py. Do not edit by hand.\n"
    "export interface SpriteAssetMeta {\n"
    "  width:number; height:number; originX:number; originY:number; visibleHeight:number;\n"
    "  frames:Partial<Record<SpriteAction,Record<string,number>>>;\n"
    "}\n"
    "export type SpriteAction='attack'|'death'|'hit'|'run'|'skill'|'stand';\n"
    f"export const SPRITE_MANIFEST = {body} as const satisfies Record<string,SpriteAssetMeta>;\n",
    encoding="utf-8",
)
print(f"Wrote {len(manifest)} sprite sets to {OUTPUT}")
