import {THEME_DESIGNS} from './core/themeDesigns';

export type Locale='zh'|'en';

const requestedLocale=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('lang'):null;
let locale:Locale=requestedLocale==='zh'?'zh':'en';
if(typeof document!=='undefined')document.documentElement.lang=locale==='zh'?'zh-CN':'en';
export const getLocale=():Locale=>locale;
export const setLocale=(value:Locale):void=>{locale=value;if(typeof document!=='undefined')document.documentElement.lang=value==='zh'?'zh-CN':'en';};

const phrases:Record<string,string>={
  // Campaign themes.
  '回声洞穴':'Echoing Caverns','遗忘地牢':'Forgotten Dungeon','沉没圣堂':'Sunken Cathedral','荒弃村庄':'Abandoned Village','焦灼地狱':'Burning Inferno',
  '断脊山道':'Broken Ridge','疫病城镇':'Plagued Town','灰冠皇宫':'Ashen Palace','王室墓窟':'Royal Catacombs','腐水下道':'Drowned Sewers',
  '霜封遗迹':'Frozen Ruins','哀嚎沼泽':'Wailing Marsh','黑铁矿井':'Black Iron Mine','流沙神殿':'Buried Temple','深渊要塞':'Abyssal Fortress',
  // Skills, ultimates, builds, and statuses shown during play.
  '连锁闪电':'Chain Lightning','幽魂旋刃':'Spectral Blades','寒霜新星':'Frost Nova','陨落余烬':'Falling Ember','穿心血矛':'Heartpiercer',
  '腐蚀迷雾':'Corrosive Mist','亡灵侍从':'Undead Retinue','白骨圣盾':'Bone Aegis','秘法飞矢':'Arcane Bolts','雷电法球':'Storm Orb',
  '尸骸爆破':'Corpse Burst','白骨长矛':'Bone Spear','裂地重斩':'Earthsplitter','铁血战吼':'Iron Warcry','回旋飞刃':'Returning Blade',
  '雷霆审判':'Storm Judgment','亡者归来':'Return of the Dead','猩红处决':'Crimson Execution','幽影闪避':'Shadow Dash',
  '雷暴共鸣':'Tempest Resonance','霜火禁域':'Frostfire Dominion','秘法棱镜':'Arcane Prism','尸潮统御':'Corpse Dominion','疫病骨矛':'Plague Spear','不死壁垒':'Undying Bastion','旋刃屠场':'Blade Slaughter','血矛回环':'Blood Lance Cycle','铁血处刑':'Ironblood Execution',
  '中毒':'Poisoned','流血':'Bleeding','眩晕':'Stunned','寒冷':'Chilled','诅咒':'Cursed','燃烧':'Burning',
  '选择你的契约者':'CHOOSE YOUR COVENANT','选择角色':'Choose character','选择此角色':'Choose character','◆ 已选定':'◆ SELECTED','诅 咒 契 约':'ACCURSED COVENANT',
  '初始技能与专属技能池':'Starting skills and exclusive skill pool','初始':'STARTING','共用行囊 · 装备与成长跨角色继承':'Shared stash · Gear and progress carry across characters',
  '天赋树':'Talent Tree','正在唤醒圣堂…':'Awakening the sanctuary…','每局可重新选择角色 · 三名角色拥有独立天赋树 · 刷新或关闭页面后清空进度':'Choose a character for every run · Each has a separate talent tree · Refreshing or closing clears all progress',
  '游戏设置':'Game settings','声音开关 [M]':'Sound [M]','关闭音效':'Mute sound','开启音效':'Enable sound','全屏':'Fullscreen','切换全屏':'Toggle fullscreen','暂停 [Esc]':'Pause [Esc]','暂停游戏':'Pause game',
  '已放逐':'BANISHED','灰烬金币':'ASH GOLD','全部金币':'TOTAL GOLD','圣堂地图':'SANCTUARY MAP','展开或收起地图':'Expand or collapse map','◆ 你':'◆ YOU','◆ 宝箱':'◆ CHEST','◆ 事件':'◆ EVENT',
  '在怪潮中成长':'Grow within the horde','收集经验，构筑你的第一个流派':'Gather essence and shape your first build','贪 欲':'GREED','地图首领':'MAP GUARDIAN',
  '生命':'Life','法力':'Mana','血瓶':'Potion','移动':'Move','装备':'Gear','请使用电脑键盘游玩 · 建议横屏或全屏':'Keyboard play recommended · Use landscape or fullscreen',
  '正在构筑地图':'FORGING THE MAP','解析随机房间与碰撞…':'Resolving random rooms and collision…','地图已完成':'Map complete','唤醒怪物与光效…':'Awakening monsters and effects…',
  '烘焙高清地板与墙体…':'Baking high-resolution floors and walls…','烘焙标准地板与墙体…':'Baking standard floors and walls…','烘焙性能地板与墙体…':'Baking optimized floors and walls…','分片铺设陈列回廊…':'Laying out gallery sections…','分片烘焙高清地板…':'Baking high-resolution floor sections…','铺设房间纹样与场景物件…':'Placing chamber motifs and scenery…','读取地图种子…':'Reading map seed…',
  '契约者的行装':'Covenant Gear','关闭装备':'Close inventory','当前构筑方向：':'Current build: ','当前特殊效果':'Active special effects','战利品':'LOOT','比较与换装时战斗暂停':'Combat pauses while comparing gear',
  '行囊仍然空着':'The pack is still empty','返回战斗':'Return to battle','可用金币':'Available gold','分解装备会转为本局金币':'Salvaged gear becomes run gold',
  '流亡商人的珍藏':'The Exile Merchant’s Stock','铁匠的灰烬锻台':'The Blacksmith’s Ash Forge','结束交易':'End trade','离开锻台':'Leave forge','商人':'Merchant','铁匠':'Blacksmith','乞丐':'Beggar','远方旅客':'Distant Traveler',
  '下一道门通往何处？':'Where does the next gate lead?','踏入此门':'Enter this gate','选择后立即进入下一张地图':'Choosing immediately enters the next map',
  '从净化的圣印中选择回报':'Choose a reward from the purified seal','房间回报':'CHAMBER REWARD','接受回报':'Take reward','战斗已暂停':'Combat paused','首领封印进度':'Boss seal progress',
  '诅咒宝箱':'Cursed Chest','血誓祭坛':'Blood Oath Altar','贪 欲 祭 坛':'GREED ALTAR','猎杀契约':'Hunt Contract','限时猎杀':'Timed Hunt','完成':'Complete','失败':'Failed','接受契约':'Accept covenant','暂不接受 · 返回探索':'Decline · Return to exploration',
  '力量，理应有代价。':'Power must have a price.','当前装备品质概率':'Current gear rarity rates','普通来源　精英/首领':'Normal source　Elite/Boss','降低一阶':'Lower one rank','提高贪欲':'Raise Greed','完成祭献，返回战斗':'Complete offering and return',
  '圣堂，暂归寂静。':'The sanctuary falls silent.','你的远征已暂停。':'Your expedition is paused.','继续远征':'Continue expedition','画质档位':'Graphics quality','画面震动':'Screen shake','自动法力增幅':'Automatic mana amplification','技能自动施法':'Automatic skill casting','点击移动':'Click to move','无耗蓝基础攻击':'Mana-free basic attack','手动释放技能':'Cast skills manually','数字键手动施法':'manual number-key casting','自动施法':'automatic casting','开启':'On','关闭':'Off','高清':'High','标准':'Standard','性能':'Performance','轻微':'Low',
  '八重门扉，尽数破碎。':'All eight gates lie shattered.','你归于灰烬。':'You return to ash.','远征时间':'Run time','放逐敌人':'Enemies banished','总伤害':'Total damage','暴击率':'Critical rate','最大一击':'Largest hit','承受伤害':'Damage taken','伤害来源':'Damage sources','角色传承树':'Character legacy tree','打开天赋树':'Open talent tree','返回营地 · 更换角色':'Return to camp · Change character',
  '怪物陈列回廊 · 自由测试':'Bestiary Gallery · Free testing','北侧房间各陈列一种怪物 · 离开镜头即销毁 · 击杀后重生 · 死亡返回入口':'Each north room holds one monster · Offscreen monsters despawn · Kills respawn · Death returns you to the entrance',
  '封门围攻':'Sealed Siege','精英阵列':'Elite Formation','守住圣印':'Defend the Seal','猎杀目标':'Hunt the Target','机关杀阵':'Trap Gauntlet','宝藏伏击':'Treasure Ambush','房门封闭':'DOORS SEALED','首领圣所已经开启':'BOSS SANCTUM UNLOCKED','净化关键房间，解除首领封印':'Purify key chambers to break the boss seal','关键房间':'Key chambers','剩余敌人':'Enemies remaining',
  '已发现':'Discovered','发现 ·':'Discovered ·','圣堂已经苏醒。移动，击杀，收集灰烬。':'The sanctuary awakens. Move, kill, and gather ash.','击碎裂纹墙壁 · 发现隐藏房间':'Break the cracked wall · Reveal a hidden chamber',
  '怪物陈列回廊 · 无掉落测试区域':'Bestiary Gallery · No-drop testing area','地图守卫':'Map Guardian','击败黑暗统治者':'Defeat the Dark Sovereign','击败地图首领':'Defeat the Map Guardian',
  ' · 地图 ':' · Map ',' · 敌人 Lv.':' · Enemies Lv.',' 房间':' chambers','噩梦':'Nightmare','坚韧':'Resilient','狂乱':'Frenzied','虫群':'Swarming','易爆':'Volatile','丰饶':'Bountiful',
  '通往下一地图的出口已开启':'The exit to the next map is open','装备你的第一件战利品':'Equip your first piece of loot','按 I 打开装备 · 比较时战斗暂停':'Press I for gear · Combat pauses while comparing',
  '躲开攻击预警，保留法力用于':'Dodge telegraphed attacks and reserve mana for ','前往主路径末端的传送门 · 下一站':'Reach the portal at the end of the main path · Next: ',
  '坚守':'Hold for','离开事件区域将失败':'Leaving the event area will fail it','诅咒试炼 · 坚守此地':'Cursed Trial · Hold your ground',
  // Tutorial and common interaction copy.
  '闪避':'Dash',
  '使用 ':'Use ',' 或方向键探索房间。':' or the arrow keys to explore.','按 ':'Press ',' 穿过危险区域；拥有两次充能。':' to pass through danger; it has two charges.','受伤后按 ':'When injured, press ',' 恢复半管生命。':' to restore half your life.',
  '在入口祭坛按 ':'At the entrance altar, press ',' 调整贪欲：敌人更强、密度更高，装备品质更好。':' to adjust Greed: enemies become tougher and denser, while loot quality improves.','靠近装备按 ':'Near gear, press ',' 快捷取走，按 ':' to pick it up, then press ',' 比较词缀与特殊机制。':' to compare affixes and special mechanics.',
  '地面装备 ·':'Ground loot ·','拾取':'Pick up','战力':'Power','对比 ':'Compared with ','该槽位尚未装备':'Nothing equipped in this slot',
  '鼠标悬停查看完整属性':'Hover for full item details','物品等级':'Item Level','与已装备物品比较':'Compared with equipped item','伤害':'Damage','暴击':'Critical Chance','冷却缩减':'Cooldown Reduction','无额外词缀':'No additional affixes','售价':'Sell Value','前缀':'Prefix','后缀':'Suffix','专属':' Exclusive','空置':'Empty','尚未装备':'Not equipped',
  // Character copy on the selection screen.
  '以雷霆，审判黑夜。':'Judge the night with thunder.','死亡，只是另一种召唤。':'Death is only another summons.','让鲜血，铭刻你的誓言。':'Let blood engrave your oath.',
  '让闪电穿过怪潮，以寒霜控制距离。积蓄法力，在雷霆降临时清空战场。':'Chain lightning through the horde and use frost to control distance. Gather mana, then clear the field with thunder.',
  '驱使骸骨侍从追击敌人，以尸体引发爆炸。用骨盾与毒雾建立你的亡灵阵线。':'Command skeletal servants and detonate the fallen. Build an undead front with bone shields and poison mist.',
  '以旋刃切开包围，以血矛穿透敌阵。把握近身窗口，处决负伤敌人并汲取生命。':'Carve through encirclement with spinning blades and pierce ranks with blood lances. Execute the wounded and drain their life.',
  '雷霆术士':'Storm Sorceress','亡灵召唤师':'Necromancer','血刃骑士':'Blood Knight','黄色稀有装备':'Rare gear','高阶装备':'High-tier gear','普通':'Normal','精英':'Elite','超级精英':'Super Elite','首领':'Boss',
  '雷电 · 连锁':'Lightning · Chain','物理 · 环绕':'Physical · Orbit','冰霜 · 控制':'Frost · Control','火焰 · 范围':'Fire · Area','血系 · 穿透':'Blood · Pierce','毒素 · 持续':'Poison · Damage over time','召唤 · 追击':'Summon · Pursuit','防御 · 反击':'Defense · Counter','秘法 · 多重':'Arcane · Multishot','雷电 · 阵地':'Lightning · Zone','亡灵 · 连爆':'Undead · Chain blast','亡灵 · 穿透':'Undead · Pierce','近战 · 击退':'Melee · Knockback','防御 · 震慑':'Defense · Control','物理 · 回返':'Physical · Return',
  '闪电在附近敌人间跳跃。暴击与法力装备让雷暴持续运转。':'Lightning jumps between nearby enemies. Critical-hit and mana gear keep the storm running.','旋转刀刃周期性切割近处敌人，适合贴身突破怪群。':'Orbiting blades periodically cut nearby enemies and break through tight packs.','释放冰环伤害并减速敌人，为走位和爆发创造窗口。':'Release a frost ring that damages and slows enemies, opening a window to reposition or burst.','在敌人密集处引爆余烬，留下持续燃烧的火域。':'Detonate an ember amid clustered enemies and leave a burning field.','向目标投出穿透血矛，命中时少量恢复生命。':'Hurl a piercing blood lance and restore a little life on hit.','在前方留下毒雾，持续侵蚀敌人，适合边退边打。':'Leave corrosive mist ahead that erodes enemies while you retreat.','召唤独立寻敌的骸骨侍从，持续追击与攻击，数量随等级增加。':'Summon skeletons that seek, pursue, and attack enemies independently; their number grows with level.','周期性获得骨盾，并震伤贴近的敌人。护盾不会无限叠加。':'Periodically gain a bone shield and damage nearby enemies. The shield does not stack without limit.','向目标扇形发射秘法弹。广域增加弹数，凝聚提高穿透能力。':'Fire arcane bolts in a cone. Wide adds projectiles; Focused improves piercing.','在前方建立放电区域；终极法球同时在周围多处放电。':'Create an electrified zone ahead; the ultimate orb discharges in several nearby areas.','消耗附近遗骸引发尸爆。没有尸体时凝成一具灵骸，首领战仍可施放。':'Consume nearby remains to trigger Corpse Burst. With no corpse, form a spectral carcass so it remains usable against bosses.','释放骨矛穿透敌阵。终极形态追加两道扇形骨矛。':'Launch a bone spear through enemy ranks. Its ultimate form adds two fan-shaped spears.','向敌人方向挥出重斩并击退目标。终极形态追加余震。':'Deliver a heavy cleave toward enemies and knock them back. Its ultimate form adds an aftershock.','战吼获得护盾，同时击退并减速贴近的敌人。':'Warcry grants a shield while knocking back and slowing nearby enemies.','向前掷出重刃后返回，去程与回程均能命中敌人。':'Throw a heavy blade that returns; both passes can hit enemies.',
  '对周围敌人降下雷霆并减速，击碎范围内的敌方投射物。':'Call thunder onto nearby enemies, slow them, and destroy hostile projectiles in the area.','召回最多六名强化骸骨侍从，震伤周围敌人，并引爆附近遗骸。':'Recall up to six empowered skeletons, damage nearby enemies, and detonate nearby remains.','斩击近处敌人，对半血以下目标造成双倍伤害，命中恢复生命。':'Slash nearby enemies, deal double damage below half life, and restore life on hit.',
  '法球建立阵地，链雷清场，秘法飞矢补足单体。':'Storm Orb controls an area, Chain Lightning clears packs, and Arcane Bolts finish single targets.','先冻结敌群，再用余烬和法球持续灼烧。':'Freeze enemy groups, then burn them with Ember and Storm Orb.','多重投射、暴击链雷与寒霜控制形成安全远程构筑。':'Multishot, critical Chain Lightning, and frost control create a safe ranged build.','侍从制造尸骸，连续尸爆，骨盾保护召唤阵线。':'Minions create remains, Corpse Burst chains explosions, and Bone Aegis protects the line.','毒雾压缩敌群，骨矛贯穿，尸爆完成连锁。':'Poison mist compresses packs, Bone Spear pierces them, and Corpse Burst completes the chain.','高数量侍从与周期骨盾构成持续推进的防线。':'Numerous minions and periodic bone shields form an advancing defense.','战吼控场，旋刃贴身切割，重斩清出突破口。':'Warcry controls the field, orbiting blades cut at close range, and Cleave opens an escape route.','双重穿透与回返刃覆盖直线，旋刃处理近身敌人。':'Two piercing attacks and a returning blade cover lanes while orbiting blades handle close threats.','护盾换取贴身窗口，对受控和低生命目标连续处决。':'Use shields to create melee windows and execute controlled or wounded targets.',
  '普通品质':'Common','魔法品质':'Magic','稀有品质':'Rare','史诗品质':'Epic','套装品质':'Set','暗金品质':'Unique','传奇品质':'Legendary','魔法':'Magic','稀有':'Rare','史诗':'Epic','套装':'Set','暗金':'Unique','传奇':'Legendary','金币':'Gold','地图':'Map','剩余':'Remaining','波次':'Wave','级解锁':' unlocks','级':' Lv.',
  // Equipment slots, bases, weapons, affixes, sets and generated loot.
  '武器':'Weapon','副手':'Off-hand','头部':'Head','胸甲':'Armor','足部':'Boots','项链':'Amulet','戒指 Ⅰ':'Ring I','戒指 Ⅱ':'Ring II','基础':'Normal Base','卓越':'Exceptional','长剑':'Sword','战斧':'Axe','战锤':'Mace','匕首':'Dagger','长矛':'Spear','法杖':'Staff','魔杖':'Wand','长弓':'Bow',
  '残酷':'Cruel','迅捷':'Swift','致命':'Deadly','巨人':'of the Giant','疾风':'of the Gale','守护':'of Warding','猎魔':'of Demon Hunting','寻宝':'of Fortune',
  '守夜者':'Night Watcher','风暴使者':'Stormcaller','疫病之主':'Plague Lord','血誓骑士':'Blood Oath Knight','灰烬朝圣者':'Ashen Pilgrim',
  '守墓人的长剑':'Gravekeeper Sword','灰烬仪式刃':'Ash Ritual Blade','沉默骨盾':'Silent Bone Shield','裂纹圣典':'Cracked Codex','失落者兜帽':'Lost One’s Hood','荆棘冠冕':'Thorn Crown','守夜人胸甲':'Watcher Cuirass','暮色法衣':'Twilight Vestment','流亡者长靴':'Exile Boots','幽影踏靴':'Shadowstep Boots','月蚀吊坠':'Eclipse Pendant','不灭骨符':'Undying Bone Charm','回响指环':'Echo Ring','苍白誓约':'Pale Covenant','余烬指环':'Ember Ring','暮光印记':'Twilight Signet',
  '灰烬长剑':'Ashen Sword','守墓长剑':'Gravekeeper Sword','暮光长剑':'Twilight Sword','流亡长剑':'Exile Sword','灰烬战斧':'Ashen Axe','守墓战斧':'Gravekeeper Axe','暮光战斧':'Twilight Axe','流亡战斧':'Exile Axe','灰烬战锤':'Ashen Mace','守墓战锤':'Gravekeeper Mace','暮光战锤':'Twilight Mace','流亡战锤':'Exile Mace','灰烬匕首':'Ashen Dagger','守墓匕首':'Gravekeeper Dagger','暮光匕首':'Twilight Dagger','流亡匕首':'Exile Dagger','灰烬长矛':'Ashen Spear','守墓长矛':'Gravekeeper Spear','暮光长矛':'Twilight Spear','流亡长矛':'Exile Spear','灰烬法杖':'Ashen Staff','守墓法杖':'Gravekeeper Staff','暮光法杖':'Twilight Staff','流亡法杖':'Exile Staff','灰烬魔杖':'Ashen Wand','守墓魔杖':'Gravekeeper Wand','暮光魔杖':'Twilight Wand','流亡魔杖':'Exile Wand','灰烬长弓':'Ashen Bow','守墓长弓':'Gravekeeper Bow','暮光长弓':'Twilight Bow','流亡长弓':'Exile Bow',
  '历经灰烬洗礼的装备，增加伤害与生命上限。':'Ash-forged gear that increases damage and maximum life.','通用武器：基础属性对所有角色与技能生效。':'Universal weapon: its base attributes benefit every hero and skill.','直接攻击':'Basic attacks','普通怪':'normal enemies','概率':' chance','额外伤害':' additional damage','击晕目标':' stun the target for','暴击后使当前技能剩余冷却缩短':'Critical hits reduce the current skill cooldown by','贯穿目标，对其后方敌人造成':'pierce the target and deal','对其后方敌人造成':'deal to enemies behind it','每第五次直接攻击释放一次':'Every fifth basic attack releases a','伤害秘法新星':' damage Arcane Nova','概率弹射一次，造成':' chance to ricochet for','攻击距离提高，并对远处目标造成至多':'Attack range increases and distant targets take up to',
  '直接攻击顺劈附近一名敌人，造成 35% 伤害。':'Basic attacks cleave one nearby enemy for 35% damage.','对生命低于 30% 的普通怪造成 25% 额外伤害。':'Deal 25% additional damage to normal enemies below 30% life.','直接攻击有 12% 概率击晕目标 0.65 秒。':'Basic attacks have a 12% chance to stun the target for 0.65 seconds.','暴击后使当前技能剩余冷却缩短 12%。':'Critical hits reduce the current skill’s remaining cooldown by 12%.','直接攻击贯穿目标，对其后方敌人造成 45% 伤害。':'Basic attacks pierce the target and deal 45% damage to enemies behind it.','每第五次直接攻击释放一次 65% 伤害秘法新星。':'Every fifth basic attack releases a 65% damage Arcane Nova.','直接攻击有 18% 概率弹射一次，造成 50% 伤害。':'Basic attacks have an 18% chance to ricochet once for 50% damage.','攻击距离提高，并对远处目标造成至多 20% 额外伤害。':'Attack range increases and distant targets take up to 20% additional damage.',
  '已学天赋':'Talents learned','传奇装备拥有更高词缀上限；颜色代表品质，等级决定数值基准':'Legendary gear has higher affix limits; color shows rarity and item level sets the stat baseline.','点击已装备物品查看完整属性与当前特殊效果。':'Select equipped gear to inspect its full attributes and active effects.','尚未激活武器、套装、暗金或传奇机制。':'No weapon, set, unique, or legendary mechanic is active.','全部':'All','稀有+':'Rare+','史诗+':'Epic+','暴击变化':'Critical Chance change','冷却缩减变化':'Cooldown Reduction change','分解':'Salvage','替换将失去：':'Replacing loses: ',' 的机制':' mechanic','快捷拾取筛选':'Quick pickup filter',
  '风暴之心':'Heart of the Storm','霜行者':'Frostwalker','饥渴圣杯':'Thirsting Chalice','送葬者的脊骨':'Undertaker’s Spine','逆火王冠':'Backfire Crown','不眠守望':'Sleepless Watch','裂空回响':'Rift Echo','血路行者':'Bloodroad Walker','双星余烬':'Twin-Star Ember','荆棘圣骸':'Thorned Reliquary','贪欲之眼':'Eye of Greed',
  '链雷额外跳跃 2 次；每次施放最多 3 次暴击恢复 4 法力。':'Chain Lightning jumps 2 additional times; up to 3 critical hits per cast restore 4 mana.','闪避留下持续 3 秒的冰径，伤害并减速经过的敌人。':'Dash leaves a 3-second ice path that damages and slows enemies.','直接技能命中恢复 1 生命（每秒至多 12）；血矛伤害提高 25%。':'Direct skill hits restore 1 life, up to 12 per second; Blood Lance damage +25%.','亡灵侍从击杀后触发尸爆；尸爆不能再触发自身。':'Undead minion kills trigger Corpse Burst; Corpse Burst cannot trigger itself.','陨落余烬范围扩大 40%，持续时间延长 2 秒。':'Falling Ember area +40% and duration +2 seconds.','白骨圣盾冷却减少 30%，获得的护盾增加 40%。':'Bone Aegis cooldown -30% and shield gained +40%.','每第五次直接技能命中释放一次秘法新星。':'Every fifth direct skill hit releases an Arcane Nova.','闪避留下血痕，伤害敌人并少量恢复生命。':'Dash leaves a blood trail that damages enemies and restores a small amount of life.','亡灵侍从上限增加 2，持续时间延长 25%。':'Undead minion limit +2 and duration +25%.','陨落余烬有 25% 概率在附近再次爆发。':'Falling Ember has a 25% chance to erupt again nearby.','承受近身伤害时反弹 18% 给攻击者。':'Reflect 18% of melee damage taken to the attacker.','普通怪装备掉率提高 25%，拾取半径提高 40%。':'Normal-enemy gear drop rate +25% and pickup radius +40%.',
  '守夜者的冠冕':'Watcher’s Crown','守夜者的誓甲':'Watcher’s Oathplate','守夜者的足迹':'Watcher’s Treads','风暴之锋':'Tempest Edge','雷鸣圣典':'Thunder Codex','暴雨之眼':'Eye of the Deluge','疫王面纱':'Plague King’s Veil','腐沼法衣':'Rotmarsh Vestment','枯萎指环':'Withered Ring','血誓刃':'Blood Oath Blade','猩红重甲':'Crimson Plate','殉道骨符':'Martyr’s Bone Charm','朝圣者足迹':'Pilgrim’s Treads','灰烬印记':'Ashen Signet','归途印记':'Homeward Signet',
  '2 件：技能伤害 +12%；3 件：生命 +60。':'2 pieces: Skill damage +12%; 3 pieces: Life +60.','2 件：冷却缩减 +8%；3 件：连锁技能多跳跃 2 次。':'2 pieces: Cooldown reduction +8%; 3 pieces: Chain skills gain 2 jumps.','2 件：持续伤害 +18%；3 件：击杀扩散毒雾。':'2 pieces: Damage over time +18%; 3 pieces: Kills spread poison mist.','2 件：近战伤害 +15%；3 件：暴击恢复 1.50 生命。':'2 pieces: Melee damage +15%; 3 pieces: Critical hits restore 1.50 life.','2 件：移动速度 +10%；3 件：拾取半径 +80%。':'2 pieces: Movement speed +10%; 3 pieces: Pickup radius +80%.','套装：':' Set: ',
  '断钟者':'Bellbreaker','守夜灯杖':'Watchlamp Staff','城垒之誓':'Oath of the Bulwark','雷语者':'Thunderspeaker','疫行':'Plaguewalk','亡军权杖':'Scepter of the Dead Host','赤路':'Crimson Path','双星':'Twin Stars',
  '直接技能对生命低于 30% 的敌人伤害提高 25%。':'Direct skills deal 25% more damage to enemies below 30% life.','主动绝技消耗降低至 32 法力，冷却保持 8 秒。':'The ultimate costs 32 mana; its cooldown remains 8 seconds.','闪避时护盾至少恢复至 12 点；不会叠加或覆盖更高护盾。':'Dashing restores shield to at least 12; it never stacks or replaces a stronger shield.','每第五次直接技能命中释放 65% 伤害秘法新星。':'Every fifth direct skill hit releases a 65% damage Arcane Nova.','闪避留下伤害敌人的血痕。':'Dash leaves a blood trail that damages enemies.',
  // Talent screen and repeated talent descriptions.
  '传承天赋':'Legacy Talents','已投入':'Invested','全树约需':'Full tree costs about','毁灭':'DESTRUCTION','秘仪':'ARCANA','守御':'DEFENSE','路线':' path','第 ':'Tier ',' 阶':'','已满级':'MAX RANK','升级费用':'Upgrade cost','前置节点需要升满':'Previous node must be maxed','退回一级 · 返还':'Refund one rank · Return','完整培养目标为约 8–10 次远征；退点返还该级消耗的 50.00%。':'A full build takes about 8–10 expeditions. Refunds return 50.00% of that rank’s cost.','返回营地':'Return to camp',
  '所有伤害提高':'All damage +','暴击率提高':'Critical chance +','冷却缩减提高':'Cooldown reduction +','精英与首领伤害提高':'Elite and boss damage +','最大法力提高':'Maximum mana +','移动速度提高':'Movement speed +','商店价格降低':'Merchant prices -','最大生命提高':'Maximum life +','状态抗性提高':'Status resistance +','血瓶治疗提高':'Potion healing +','受到的伤害降低':'Damage taken -','金币获取提高':'Gold find +',' / 级。':' per rank.',
  '余烬铭刻':'Ember Inscription','过载回路':'Overload Circuit','雷霆导体':'Storm Conduit','元素穿刺':'Elemental Pierce','灾变增幅':'Cataclysmic Force','无尽雷暴':'Endless Tempest','秘法回流':'Arcane Reflux','法力容器':'Mana Vessel','相位步法':'Phase Step','奥术专注':'Arcane Focus','符文议价':'Runic Bargain','执政官回响':'Archon Echo','寒冰护体':'Frost Ward','元素沉静':'Elemental Calm','炼金血剂':'Alchemical Tonic','结晶外壳':'Crystal Shell','秘能储备':'Arcane Reserve','棱晶壁垒':'Prismatic Bulwark',
  '骨文研习':'Ossuary Study','灵魂收割':'Soul Harvest','墓穴恶意':'Crypt Malice','疫火灌注':'Plaguefire Infusion','死神凝视':'Reaper’s Gaze','亡军冠冕':'Crown of the Dead','迅捷仪式':'Swift Ritual','丰饶祭品':'Bountiful Offering','亡者行军':'March of the Dead','灵魂容器':'Soul Vessel','亡者低语':'Whispers of the Dead','永夜契约':'Eternal Night Covenant','借尸还魂':'Borrowed Flesh','疫病适应':'Plague Adaptation','尸花药剂':'Corpsebloom Elixir','骸骨甲片':'Bone Carapace','不朽骨髓':'Immortal Marrow','骨甲王座':'Bone Throne',
  '血刃磨砺':'Blood Edge','猎首者':'Headhunter','猩红渴望':'Crimson Thirst','撕裂锻炼':'Rending Discipline','行刑者':'Executioner','猩红狂热':'Crimson Frenzy','战场步法':'Battlefield Step','染血战利品':'Bloodied Spoils','连斩节奏':'Slayer’s Rhythm','战意储备':'Battle Reserve','佣兵门路':'Mercenary Contacts','无休猛攻':'Relentless Assault','铁血体魄':'Ironblood Vigor','烈性血瓶':'Potent Blood Flask','钢铁意志':'Iron Will','染血锁甲':'Bloodied Mail','巨像血脉':'Colossus Blood','重甲誓约':'Platebound Oath',
  // Skill evolutions and build linkage.
  '分裂雷网':'Forked Thunderweb','裁决雷核':'Judgment Core','逐猎飞刃':'Hunting Blades','贴身绞杀':'Close Quarters Maelstrom','永冻环域':'Permafrost Halo','极寒之心':'Heart of Absolute Frost','焚城余烬':'Cityburn Ember','坠星熔核':'Falling Star Core','血潮贯阵':'Bloodtide Phalanx','噬心血枪':'Heart-Eater Lance','腐国迷雾':'Kingdom of Blight','蚀骨毒沼':'Bone-Eating Mire','骸骨军团':'Skeletal Legion','骸骨冠军':'Skeletal Champion','白骨城垒':'Bone Citadel','不破骨铠':'Unbroken Boneplate','秘法弹幕':'Arcane Barrage','贯界飞矢':'Worldpiercer Bolts','雷云领域':'Thundercloud Domain','超载雷核':'Overload Core','尸潮连爆':'Corpsechain Detonation','骸骨炸弹':'Ossuary Bomb','骨矛方阵':'Bone Spear Phalanx','葬王骨枪':'Kingburial Spear','裂地横扫':'Earthrending Sweep','断首重斩':'Decapitating Cleave','军团怒吼':'Legion Warcry','三路回刃':'Three-Way Return','追魂飞刃':'Soulseeker Blade',
  '当前构筑联动':'ACTIVE BUILD LINKS','条已激活':' active','天赋倾向':'Talent focus','等待进化':'Awaiting evolution','终极':'Apex','清群':'Crowd clear','回返':'Returning','近战':'Melee','控制':'Control','冻结':'Freeze','范围':'Area','爆发':'Burst','穿透':'Pierce','吸血':'Life steal','持续':'Damage over time','腐蚀':'Corrosion','数量':'Legion','精锐':'Champion','防线':'Defense','护盾':'Shield','多重':'Multishot','阵地':'Zone','连锁':'Chain','单体':'Single target','破甲':'Armor break','击退':'Knockback','处决':'Execute','控场':'Control','生存':'Survival','扇形':'Fan',
  '霜火联动 · 寒冷目标承受的陨落余烬伤害 +25%':'Frostfire link · Falling Ember deals +25% damage to chilled targets','亡军联动 · 三名侍从在场时尸骸爆破伤害 +22%':'Dead Host link · Corpse Burst damage +22% while three minions are active','铁血联动 · 有护盾时裂地重斩伤害 +20%':'Ironblood link · Earthsplitter damage +20% while shielded','已与技能构筑联动':'linked to the active skill build','装备对应的传奇机制或组合技能后，将在这里显示联动。':'Equip a matching legendary mechanic or skill combination to reveal build links here.','构筑联动':'BUILD SYNERGY','强化 ':'Empowers ','尚未与当前技能直接联动':'No direct link to the current skills','天赋 ':' talents ','级 ·':' ranks ·','正在放大该装备的':'Amplifying this item’s ','投入该分支后可进一步放大属性':'Invest in this branch to amplify the item','攻击属性':'offensive attributes','冷却属性':'cooldown attributes','生存属性':'survival attributes',
  '额外跳跃 2 次，单段伤害降低 15%，优先覆盖更多目标。':'Gain 2 jumps; each hit deals 15% less damage and prioritizes wider coverage.','伤害提高 35%，剩余跳跃转化为对首要目标的追加伤害。':'Damage +35%; unused jumps become additional damage to the primary target.','旋刃改为向外飞出并返回，可从安全距离持续切割。':'Blades fly outward and return, cutting enemies from a safer distance.','伤害提高 35%，保留贴身环斩与更稳定的命中覆盖。':'Damage +35%; retain the close orbit for reliable coverage.','冰环半径扩大 30%，更适合控制大群敌人。':'Frost ring radius +30% for controlling large groups.','伤害提高 35%，寒冷持续时间显著延长。':'Damage +35% and Chill lasts much longer.','燃烧区域扩大 30%，覆盖更多通道与怪群。':'Burning area +30% to cover more lanes and packs.','伤害提高 35%，将火力集中在较小区域。':'Damage +35% and concentrate fire in a smaller area.','血矛额外贯穿 3 名敌人，适合直线怪群。':'Blood Lance pierces 3 additional enemies.','伤害提高 35%，强化单体吸血与处决能力。':'Damage +35% with stronger single-target life steal and execution.','毒雾范围扩大 30%，持续封锁更宽阔的区域。':'Poison mist area +30% for wider denial.','伤害提高 35%，毒雾集中并快速侵蚀目标。':'Damage +35%; concentrated mist erodes targets faster.','召唤上限增加 1 名，以数量建立前线。':'Minion limit +1, creating a larger front line.','侍从伤害提高 35%，以精锐单位追击强敌。':'Minion damage +35%, turning them into elite hunters.','震击半径扩大 30%，保护更大的近身区域。':'Shock radius +30% to protect a wider close-range area.','技能伤害提高 35%，并获得更厚的个人护盾。':'Skill damage +35% and gain a stronger personal shield.','额外发射 2 枚飞矢，形成更宽的扇形弹幕。':'Fire 2 additional bolts in a wider fan.','伤害提高 35%，每枚飞矢额外贯穿 3 名敌人。':'Damage +35%; each bolt pierces 3 additional enemies.','放电区域扩大 30%，适合长时间封锁战场。':'Discharge area +30% for sustained battlefield control.','伤害提高 35%，法球集中轰击较小区域。':'Damage +35%; the orb bombards a tighter area.','爆炸半径扩大 30%，并一次消耗最多 5 具遗骸。':'Blast radius +30% and consume up to 5 remains.','伤害提高 35%，集中引爆距离目标最近的遗骸。':'Damage +35% and detonate the remains nearest the target.','骨矛额外贯穿 3 名敌人，覆盖完整敌阵。':'Bone Spear pierces 3 additional enemies.','伤害提高 35%，强化对精英与首领的单体打击。':'Damage +35% against priority targets.','斩击半径扩大 30%，清出更宽的突破口。':'Cleave radius +30%, opening a wider escape route.','伤害提高 35%，集中斩击鼠标方向的敌人。':'Damage +35%, focused toward the cursor.','震慑半径扩大 30%，击退并减速更大范围敌人。':'Control radius +30%, knocking back and slowing more enemies.','回旋飞刃变为三路扇形投掷，覆盖更多敌人。':'Throw returning blades in a three-way fan.','伤害提高 35%，强化正面飞刃的贯穿伤害。':'Damage +35% and strengthen the forward blade.',
  '万雷织网：额外获得 3 次跳跃。':'Thunderweb Apex: gain 3 additional jumps.','天罚回响：最后一次命中再次轰击首要目标。':'Judgment Echo: the final hit strikes the primary target again.','五星轮舞：飞刃数量增加至 5 枚。':'Five-Star Dance: increase the blade count to 5.','双重绞杀：环斩后追加一次反向斩击。':'Double Maelstrom: follow the orbiting slash with a reverse strike.','霜原残响：留下大范围持续冰域。':'Frozen Expanse: leave a large persistent frost field.','绝对零度：冻结中心敌人并留下高伤冰域。':'Absolute Zero: freeze central enemies and leave a high-damage frost field.','陨火群落：额外生成两处燃烧区域。':'Meteor Colony: create two additional burning areas.','熔核震爆：落地时立即造成一次爆发伤害。':'Core Impact: deal immediate burst damage on landing.','三叉血潮：同时投出三根血矛。':'Trident Bloodtide: throw three blood lances.','心脉贯穿：主血矛伤害额外提高 25%。':'Heartpiercer Apex: main Blood Lance damage +25%.','瘟疫蔓延：额外生成两片毒雾。':'Spreading Plague: create two additional poison mists.','剧毒迸发：施放时立即侵蚀区域内敌人。':'Toxic Eruption: immediately damage enemies in the area.','亡军列阵：再增加 1 名侍从并延长持续时间。':'Dead Host Formation: gain 1 more minion and extend duration.','死者先锋：侍从攻击造成更强硬直。':'Vanguard of the Dead: minion attacks cause stronger stagger.','骸骨圣域：获得护盾时释放第二次外环震击。':'Bone Sanctuary: gaining shield releases a second outer shock.','不朽甲胄：护盾量额外提高 35%。':'Immortal Plate: shield gained +35%.','七星棱镜：再增加 2 枚飞矢。':'Seven-Star Prism: fire 2 more bolts.','棱镜重叠：中心飞矢造成一次追加命中。':'Prism Overlap: the central bolt scores an additional hit.','群星布雷：额外建立两处小型雷区。':'Stormfield: establish two additional small lightning zones.','雷核坍缩：施放时立即释放一次电击。':'Core Collapse: release an immediate electric strike.','葬场共鸣：每具遗骸引发更宽的连锁爆炸。':'Graveyard Resonance: every corpse creates a wider chained blast.','血肉压缩：主爆炸追加一次中心震爆。':'Compressed Flesh: the main blast adds a central detonation.','三重骨阵：同时释放三道骨矛。':'Triple Bone Phalanx: launch three bone spears.','王骨贯心：主骨矛伤害额外提高 25%。':'Kingbone Pierce: main Bone Spear damage +25%.','大地余震：斩击后留下范围余震。':'Earth Aftershock: leave an area aftershock after the cleave.','行刑回斩：对低生命敌人追加一次斩击。':'Execution Reprise: strike low-life enemies again.','战场回声：短暂延续减速与压制区域。':'Battlefield Echo: briefly sustain a slowing control zone.','不屈战魂：护盾量额外提高 35%。':'Unbroken Spirit: shield gained +35%.','六刃归潮：回返时获得额外穿透。':'Six-Blade Return: returning blades gain additional piercing.','往返绝杀：回程伤害进一步提高。':'Killing Return: increase damage on the return pass.',
  '基础伤害额外提高 40%。':'Base damage gains an additional 40%.','升至 6 级并强化技能规模。':'Reach level 6 and strengthen the skill form.',
  '元素共鸣':'Elemental Resonance','魂火':'Soulfire','血怒':'Bloodrage','已充满 · 下一次核心行动获得强化':' is full · the next core action is empowered','释放':' released',
  '施放技能与暴击积蓄；充满后下一次技能进入元素过载。':'Build through skill casts and critical hits; at full charge, the next skill Overloads.','击杀与消耗遗骸积蓄；充满后强化召唤或尸骸爆破。':'Build through kills and consumed remains; at full charge, empower Summon or Corpse Burst.','攻击与承受伤害积蓄；充满后强化下一次武技并恢复生命。':'Build by attacking and taking damage; at full charge, empower the next martial action and restore Life.',
  '之契':' Covenant','获得 18% 范围、1 个额外目标或投射物，冷却缩短 8%。':' gains 18% area, one extra target or projectile, and 8% cooldown reduction.','伤害提高 22%，冷却缩短 8%。':' damage +22% and cooldown -8%.',
  '第三次连续攻击变为重斩；每次攻击顺劈附近一名敌人。':'The third consecutive attack becomes a heavy slash; every attack cleaves one nearby enemy.','大范围重击；对生命低于 30% 的普通怪造成 25% 额外伤害。':'A wide heavy strike; deal 25% additional damage to normal enemies below 30% Life.','沉重攻击有 24% 概率击晕目标 0.65 秒。':'Heavy attacks have a 24% chance to stun for 0.65 seconds.','每次攻击追加 55% 伤害的副手刺击；暴击缩短技能冷却 12%。':'Every attack adds a 55% off-hand strike; critical hits reduce skill cooldowns by 12%.','窄幅远距突刺，贯穿目标并对其后方敌人造成 45% 伤害。':'A narrow long-range thrust that pierces and deals 45% damage behind the target.','发射贯穿法弹；每第五次攻击释放一次 65% 伤害秘法新星。':'Fire piercing arcane bolts; every fifth attack releases a 65% damage Arcane Nova.','快速发射双生魔弹；直接攻击有 18% 概率弹射一次。':'Rapidly fire twin bolts; basic attacks have an 18% chance to ricochet once.','远距穿透射击；距离超过 220 时造成 20% 额外伤害。':'A long-range piercing shot; deal 20% additional damage beyond 220 range.'
  // Remaining interface, combat, encounter, and generated-theme copy.
  ,'中文 / English':'Chinese / English','切换中英文':'Switch language','地图：青色为你，红色为祭坛，金色为未开启宝箱':'Map: cyan is you, gold is an unopened chest, and red is an event'
  ,'第一阶段 · 魔王降临':'Phase One · The Dark Lord Descends','第二阶段 · 碎彩窗':'Phase Two · Shattered Glass','第三阶段 · 末日丧钟':'Phase Three · Doomsday Bell'
  ,'选择新的力量':'Choose a New Power','让灰烬为你所用':'Bend the Ash to Your Will','技能由你决定。选取一项，加入自动施放序列。':'Choose your skill and add it to the automatic casting sequence.','选择一项强化。已装备技能始终有可选的成长路径。':'Choose an upgrade. Every equipped skill retains a valid growth path.','全新技能':'NEW SKILL','技能分支':'SKILL BRANCH','契约强化':'COVENANT UPGRADE','击败敌人或开启地图中的宝箱。':'Defeat enemies or open chests found throughout the map.'
  ,'怪物陈列回廊已经解锁，传送门位于营地。':'The Bestiary Gallery is unlocked. Its portal stands in camp.','输入六位旧日编号':'Enter the six-digit ancient code','确认暗号':'Confirm code','已匹配':'Matched','当前上限':'Current cap','没有可锻造的装备。':'No equipment is available for forging.','幸存者营火：进入时补满生命、法力和血瓶':'Survivor campfire: fully restores Life, Mana, and potions on entry'
  ,'开启后，在紫色契约圈内存活 25 秒。离开契约圈将失败。':'After activation, survive inside the violet covenant circle for 25 seconds. Leaving the circle fails the event.','献出最大生命的 30%，立即获得一件受当前贪欲上限约束的高品质装备。':'Sacrifice 30% of maximum Life to immediately gain high-quality gear limited by the current Greed cap.','在紫色契约圈内，40 秒内击杀 18 名敌人；离开契约圈或超时将失败。':'Kill 18 enemies inside the violet covenant circle within 40 seconds. Leaving or running out of time fails the event.','战斗中可自由撤离，但事件不能重新开启。':'You may withdraw during combat, but the event cannot be restarted.'
  ,'最终魔王':'Dark Sovereign','远征中的危险':'the dangers of the expedition','冷却':'Cooldown','攻击':'Offense','已售出':'SOLD'
  ,'基础攻击':'Basic Attack','副手刺击':'Off-hand Strike','隐藏回廊已经回应 · 特殊传送门出现在营地':'The hidden gallery answers · A special portal appears in camp','怪物陈列回廊 · 门前铭文标记了每个试炼目标':'Bestiary Gallery · Inscriptions before each door identify its trial target','你离开了怪物陈列回廊':'You left the Bestiary Gallery','购买血瓶 · 已放入药剂腰带':'Potion purchased · Added to the potion belt'
  ,'房间机关':'Chamber Device','房间净化':'Chamber Purified','守护者遗物':'Guardian Relic','获得一件至少稀有品质、匹配当前等级的装备。':'Gain level-matched equipment of Rare quality or better.','灰烬贡金':'Ash Tribute','圣所休整':'Sanctuary Respite','恢复 45% 生命、40 法力并补充一瓶血瓶。':'Restore 45% Life and 40 Mana, and replenish one potion.','关键房间已经净化 · 首领圣所解除封锁':'Key chambers purified · Boss Sanctum unsealed'
  ,'地刺机关启动':'Spike trap activated','霜息机关启动':'Frost vent activated','焰口机关启动':'Flame vent activated','陈列回廊重塑了你的躯体':'The Gallery restores your body','召唤物':'Minion','格挡':'BLOCKED','打断':'INTERRUPTED','最终守卫已经陨落':'The final guardian has fallen','地图首领已被击败 · 出口已经开启':'Map Guardian defeated · The exit is open','最终首领':'Final Boss','怪物':'Monster'
  ,'远程攻击':'Ranged Attack','投射物':'Projectile','持续区域':'Persistent Area','敲钟人的钟波':'Bellringer Shockwave','诅咒领域':'Cursed Domain','环境':'Environment','精英骑士的冲锋':'Elite Knight Charge','第三阶段':'Phase Three','末日丧钟':'Doomsday Bell','第二阶段':'Phase Two','碎彩窗':'Shattered Glass'
  ,'圣骸震波':'Sacred Remains Shockwave','碎彩陨火':'Shattered-Glass Meteor','亡者弥撒':'Mass of the Dead','荆棘囚笼':'Thorn Prison','审判圣光':'Judgment Light','腐化圣油':'Corrupted Holy Oil','钟楼坠击':'Belfry Slam','殉道冲锋':'Martyr Charge','裂魂箭雨':'Soul-Rending Volley','断罪':'Condemnation','灾厄仪式':'Calamity Ritual','跃向目标':'Leap to Target','发动冲锋':'Begin Charge'
  ,'疫病城镇 · 在幸存者营火旁完成休整':'Plagued Town · Rest beside the survivor campfire','生命不足，无法完成献祭':'Not enough Life to complete the sacrifice','诅咒开启 · 在此地存活 25 秒，离开将失败':'Curse awakened · Survive here for 25 seconds; leaving fails the event','猎杀开始 · 40 秒内击败附近 18 个敌人':'Hunt started · Defeat 18 nearby enemies within 40 seconds','契约失败 · 你离开了事件区域':'Covenant failed · You left the event area','猎杀契约超时':'Hunt Contract expired','稀有及以上':'Rare or Better','史诗及以上':'Epic or Better'
  ,'背包已满，新增装备自动分解为灰烬金币':'Inventory full · New equipment was salvaged into Ash Gold','饮下血瓶 · 恢复 50% 生命':'Potion consumed · Restored 50% Life','离开怪物陈列回廊':'Leave the Bestiary Gallery','进入怪物陈列回廊':'Enter the Bestiary Gallery','贪欲祭坛':'Greed Altar','与商人交易':'Trade with the Merchant','委托铁匠锻造':'Ask the Blacksmith to forge','听听乞丐的请求':'Hear the Beggar’s request','与远方旅客交谈':'Speak with the Distant Traveler'
  ,'触碰复苏神龛':'Touch the Restoration Shrine','打碎封印陶罐':'Break the Sealed Urn','拉动远古机关':'Pull the Ancient Mechanism','开启金币宝箱':'Open Gold Chest','开启遗物宝箱':'Open Relic Chest','暗墙崩裂 · 隐藏房间已经开启':'Hidden wall shattered · Secret chamber revealed','神龛恢复了生命':'The shrine restored Life','陶罐中藏有战利品':'The urn contained loot','远古机关压制了附近敌人':'The ancient mechanism suppressed nearby enemies','遗物宝箱已开启 · 获得装备并补充一瓶药剂':'Relic chest opened · Equipment gained and one potion replenished'
  ,'终极蜕变':'Apex Evolution','强化':'Upgrade','灰烬的恩赐':'Gift of Ash','恢复 40% 生命并补充一瓶药剂。':'Restore 40% Life and replenish one potion.','贯穿':'Piercing','伤害提高 35%，并获得更厚的个人护盾。':'Damage +35% and gain a stronger personal shield.'
  // Theme relics.
  ,'回声晶核':'Echo Crystal Core','盲蛛女王之牙':'Blind Spider Queen Fang','典狱长的断钥':'Warden’s Broken Key','无罪者铁枷':'Innocent’s Iron Shackle','殉道者圣徽':'Martyr’s Holy Emblem','无声唱诗冠':'Silent Choir Crown','最后一盏家灯':'Last Hearthlight','狼疫村契':'Wolfplague Village Pact','不灭狱心':'Undying Infernal Heart','焚世君王角':'Worldburner King’s Horn'
  ,'断脊峰印':'Broken Ridge Sigil','雪葬猎王披风':'Snowburied Huntmaster Cloak','封城执政印':'Sealed City Magistrate Sigil','疫医最后的药箱':'Plague Doctor’s Last Kit','灰冠残片':'Ashen Crown Fragment','末代禁卫誓剑':'Last Royal Guard Oathblade','无名王子指骨':'Nameless Prince’s Fingerbone','王陵守夜灯':'Royal Tomb Watchlamp','毒潮阀芯':'Toxic Tide Valve','腐壳母巢囊':'Rot-Shell Brood Sac'
  ,'永冬星核':'Everfrost Star Core','霜王碎冕':'Frost King’s Broken Crown','女巫泥心':'Witch’s Mire Heart','沉船引魂灯':'Wrecked Soul Lantern','黑铁母矿':'Black Iron Motherlode','塌方者鸣镐':'Cavebreaker Pick','葬日金盘':'Sun-Burial Disk','法老蝎尾印':'Pharaoh’s Scorpion Seal','深渊军令':'Abyssal War Order','裂隙凝视之眼':'Rift-Gazing Eye'
  // Theme encounter formations.
  ,'蛛鼠群':'Spider-Rat Swarm','甲虫楔阵':'Beetle Wedge','伏地猎群':'Crawling Huntpack','盾矛狱阵':'Prison Shieldwall','死囚突击':'Condemned Assault','傀儡看守':'Puppet Wardens','圣卫盾线':'Holy Guard Line','亡魂送葬列':'Spirit Funeral March','寒歌唱诗班':'Frostsong Choir','疫尸邻里':'Plague-Dead Neighbors','狼人狩猎队':'Werewolf Hunting Party','荒园伏击':'Ruined Garden Ambush'
  ,'恶魔双翼':'Demon Twin Wings','地狱重阵':'Infernal Heavy Formation','火蛛猎群':'Fire-Spider Huntpack','狼群包抄':'Wolfpack Envelopment','巨怪前锋':'Ogre Vanguard','牛头山卫':'Minotaur Mountain Guard','尸群漫街':'Dead Horde in the Streets','狼人巷战':'Werewolf Street Fight','暗巷猎杀':'Alley Hunt','王庭盾阵':'Royal Shieldwall','禁卫处刑队':'Royal Execution Squad','恶魔廷臣':'Demon Courtiers'
  ,'盾矛亡军':'Dead Shield-and-Spear Host','墓道追猎':'Crypt Passage Hunt','领主送葬队':'Lord’s Funeral Guard','飞虫毒群':'Venomous Flier Swarm','臭虫壁垒':'Stinkbug Bulwark','管道伏击':'Pipe Ambush','雪狼追猎':'Snow Wolf Hunt','冰法盾群':'Frost Mage Shieldpack','寒魂突袭':'Cold Spirit Assault','毒蛇猎圈':'Serpent Hunting Ring','飞虫毒幕':'Venomous Flier Screen','蛛网花巢':'Web-Bloom Nest'
  ,'钻地虫群':'Burrower Swarm','甲虫矿壁':'Beetle Minewall','牛头监工队':'Minotaur Overseers','蝎蛇围猎':'Scorpion-Serpent Hunt','神殿盾军':'Temple Shield Host','火法献祭队':'Fire Mage Sacrificial Guard','恶魔战楔':'Demon Battle Wedge','领主突击队':'Lord’s Assault Squad','鬼武折跃队':'Ghost Warrior Warp Squad'
  // Dynamic template fragments retain their punctuation so interpolated values
  // read naturally after localization.
  ,'以':'Enter as ','进入圣堂':' · Enter the Sanctuary','圣堂暂时无法打开':'The sanctuary cannot be opened yet','加载未完成':'Loading Incomplete','重新加载':'Reload'
  ,' 秒冷却 · ':'s cooldown · ',' 法力，8 秒冷却。':' Mana, 8s cooldown.','闪避 [Space]：两次充能，短暂无敌':'Dash [Space]: two charges with brief invulnerability',' 秒 · 敌人 ':'s · Enemies ',' 秒 · 离开事件区域将失败':'s · Leaving the event area fails it',' · 施法：':' · Casting: '
  ,'装备拥有更高词缀上限；颜色代表品质，等级决定数值基准':'Equipment has higher affix limits; color indicates rarity and level sets the stat baseline','契约正在回应':'The covenant is answering','选择此契约':'Choose this covenant','选择后继续':'Choose to continue'
  ,'已装备':'Equipped','背包':'Inventory','将鼠标放在物品图标上查看属性':'Hover over an item icon to view its attributes','套装与传奇效果会显示在左侧角色栏':'Set and Legendary effects appear in the character panel on the left'
  ,'每件商品显示完整底材、属性、词缀、武器机制和与已装备物品的差值。':'Each item shows its base, attributes, affixes, weapon mechanic, and comparison with equipped gear.','当前地图':'Current map','贪欲':'Greed','浓缩生命药剂':'Concentrated Life Potion','立即补充一格腰带库存 · 当前':'Immediately add one potion to the belt · Current','库存':'Stock','商人低声说：“有些货物，只回应正确的旧日编号。”':'The merchant whispers: “Some wares answer only to the correct ancient code.”'
  ,'调校只补足落后的物品等级；升品保留装备槽位与武器种类，并重新生成对应品质属性。':'Tuning raises only an outdated item level; rarity upgrades preserve the slot and weapon type, then reroll attributes for the new rarity.','匹配至 Lv.':'Match to Lv.','提升品质':'Upgrade Rarity'
  ,'冻饿的乞丐':'The Starving Beggar','“给我一半盘缠。我若能越过下一道门，会以旅客的身份三倍偿还。”':'“Give me half your coin. If I cross the next gate, I will return threefold as a traveler.”','支付 ':'Pay ','下一地图返还 ':'Returned next map: ','交出一半金币':'Give Half Your Gold','拒绝并离开':'Refuse and Leave'
  ,'来自远方的旅客':'Traveler from Afar','褴褛已经换成了远行披风。他记得你在上一道门前的选择。':'His rags are now a traveler’s cloak. He remembers your choice at the previous gate.','收下约定的三倍回报':'Claim the Promised Threefold Return'
  ,'路线会改变场景、怪物族群、首领池与机关组合。角色、技能和装备继续保留。':'The route changes the environment, monster families, boss pool, and device combinations. Your character, skills, and equipment carry on.',' 个房间':' chambers'
  ,'每个房间只会回应一次。选择会立即生效，然后继续探索。':'Each chamber answers only once. Your choice takes effect immediately before exploration resumes.','奖励 · ':'Reward · ','需要 ':'Requires ',' 生命；必须保留至少 1 点生命。':' Life; at least 1 Life must remain.'
  ,'贪欲提高怪物生命、攻击、防御和密度，并把装备品质概率推向更高等级；怪物与装备等级保持不变。':'Greed increases monster Life, offense, defense, and density while shifting equipment rarity toward higher tiers. Monster and equipment levels remain unchanged.','当前贪欲 / 15':'Current Greed / 15','怪物防御':'Monster Defense','额外怪潮':'Additional Hordes','各级怪物掉装率：':'Equipment drop rate by monster tier:','；下列为掉出装备后的品质占比':'; values below are rarity shares after equipment drops','贪欲 0–9：紫色史诗及以上为 0%。精英与超级精英使用各自掉装率；地图首领和最终首领必定掉落，并使用右列概率；固定品质宝箱和事件不参与随机计算。':'Greed 0–9: Epic and higher rarity has a 0% chance. Elite and Super Elite monsters use their own drop rates; Map Guardians and Final Bosses always drop equipment and use the right column. Fixed-rarity chests and events do not use this roll.'
  ,'左键 / WASD':'Left Click / WASD','右键':'Right Click','两次充能':'Two Charges','恢复半管生命':'Restore Half Life','开箱 / 祭坛':'Chests / Altars','拾取最近装备':'Pick Up Nearest Gear','装备与分解':'Gear & Salvage','展开地图':'Expand Map','关闭后使用数字键 1–4，技能默认朝鼠标方向释放':'When off, use number keys 1–4; skills cast toward the cursor','高清使用更清晰地形；性能档减少环境光效与活跃地块':'High uses sharper terrain; Performance reduces environmental effects and active tiles','重击停顿保持，震动强度可单独调整':'Hit-stop remains active; screen shake intensity is adjusted separately','技能仅在有余量时消耗 12 法力':'Skills consume 12 Mana only when enough is available'
  ,'通关奖励':'Completion Reward','已解锁并自动装备':'Unlocked and equipped automatically','你穿越八张地图并击败了':'You crossed eight maps and defeated ','倒在地图 ':'Fell on map ',' / 8。最后的威胁：':' / 8. Final threat: ','本局金币':'Run Gold','会话金币':'Session Gold','所有成长仅在当前页面有效；刷新或关闭页面后清空。':'All progression lasts only for this browser session; refreshing or closing the page clears it.'
  ,'/3：套装效果已激活':'/3: Set effect active','属性':'Attributes','机制需要 ':'Mechanic requires ','；基础属性仍生效。':'; base attributes remain active.','查看 ':'View '
  // Dynamic combat, encounter, and interaction notifications.
  ,'首领圣所尚未开启 · 净化关键房间 ':'Boss Sanctum locked · Purify key chambers ','商人成交 · ':'Merchant purchase · ','铁匠调校 · ':'Blacksmith tuning · ','提升至 ':'raised to ','铁匠升品 · ':'Blacksmith rarity upgrade · ','成为':' became ','你交给乞丐 ':'You gave the beggar ',' 金币。他答应在下一道门后偿还。':' Gold. He promises repayment beyond the next gate.','远方旅客履约 · 归还 ':'The distant traveler honors the bargain · Returned '
  ,' · 房门已经封闭':' · Doors sealed','房间已净化 · ':'Chamber purified · ',' · 首领封印 ':' · Boss seal ','立即获得 ':'Immediately gain ','造成的':' inflicted ','打断成功 · ':'Interrupt successful · ','的施法被粉碎':'’s cast was shattered'
  ,'专属遗物 · ':'Exclusive Relic · ','传奇现世 · ':'Legendary Found · ','暗金遗物 · ':'Unique Relic · ','套装部件 · ':'Set Piece · ','的近身攻击':'’s melee attack'
  ,'进入第三阶段 · 末日丧钟':'Phase Three begins · Doomsday Bell','进入第二阶段 · 碎彩窗':'Phase Two begins · Shattered Glass','正在施放 ':'Casting ',' · 重击或暴击可打断':' · Heavy attacks or critical hits can interrupt','释放扩散冲击 · 穿越波纹':'Expanding shockwave released · Pass through the wave','锁定陨火 · 离开灼烧区域':'Meteor locked on · Leave the burning area','召集仆从':'Summoning Minions','编织三面囚笼 · 从缺口突围':'Weaving a three-sided prison · Escape through the opening','蓄积毁灭射线':'Charging Annihilation Ray','喷吐腐化毒池':'Spewing a Corrupted Poison Pool'
  ,'陈列室':'Gallery Chamber','隐藏精英 · ':'Hidden Elite · ','守卫':'Guardian','苏醒':' awakens','现身':' appears','进入第 ':'Enter Floor ',' 层 · ':' · ','契约完成 · ':'Covenant complete · ','与 60 金币':' and 60 Gold','快捷拾取 · ':'Quick pickup · ','已装备 · ':'Equipped · ','法力不足 · ':'Not enough Mana · ','进入下一地图 · ':'Entering next map · ','金币宝箱已开启 · 获得 ':'Gold chest opened · Gained ',' 阶 · 怪潮与奖励已改变':' · Hordes and rewards changed','升至 ':'Reached ',' 级，提高基础伤害与技能效果。':' and increased base damage and skill effects.'
  // QA controls, loading failures, renderer labels, and cosmetics.
  ,'开发者调试面板':'Developer QA Panel','DEMO 0.15 调试台':'DEMO 0.15 QA Console','地图主题':'Map Theme','载入地图主题':'Load Map Theme','进入下层':'Enter Next Floor','等级 +5':'Level +5','生成怪群':'Spawn Pack','生成精英':'Spawn Elite','唤醒 Boss':'Awaken Boss','清除怪物':'Clear Monsters','生成装备':'Spawn Gear','生成装备品质':'Spawn Gear Rarity','无敌：关':'Invincible: Off','无敌：':'Invincible: ','开':'On','关':'Off','仅开发环境与 ?qa=1 可见，不写入浏览器存档。':'Visible only in development and with ?qa=1; does not write browser saves.','等级 ':'Level ','敌人 ':'Enemies ','承伤 ':'Damage Taken '
  ,'当前浏览器未能进入全屏，可使用浏览器全屏快捷键。':'The browser could not enter fullscreen. Use the browser fullscreen shortcut instead.','游戏素材未能加载，请检查网络后重试。':'Game assets failed to load. Check your connection and try again.','画质 · ':'Quality · ','技能自动施法已开启':'Automatic skill casting enabled','技能自动施法已关闭 · 使用 1–4 手动施法':'Automatic skill casting disabled · Use 1–4 to cast manually','附近没有可拾取且符合筛选的装备':'No nearby equipment matches the pickup filter','需要支持 WebGL 的浏览器。请开启浏览器硬件加速，或尝试较新的 Chrome、Edge、Firefox。':'A WebGL-capable browser is required. Enable hardware acceleration or use a recent version of Chrome, Edge, or Firefox.'
  ,'烘焙':'Baking ','地板与墙体…':'floors and walls…','陨石':'Meteor','塌':'Collapse','灰烬羽翼 ':'Ashen Wings '
  // Bestiary display names used by the gallery labels and combat messages.
  ,'黑巨怪':'Black Ogre','蓝恶魔':'Blue Demon','獠牙猪怪':'Tusked Boarfiend','牛魔':'Bull Demon','遁地蜘蛛':'Burrowing Spider','遁地虫':'Burrowing Worm','洞穴蝾螈':'Cave Salamander','爬行丧尸':'Crawling Zombie','双刀恶魔':'Twinblade Demon','精英恶魔':'Elite Demon','腐壳虫王':'Rot-Shell Broodlord','精英牛头人':'Elite Minotaur','精英骷髅':'Elite Skeleton','火蜘蛛':'Fire Spider','鬼武士':'Ghost Samurai'
  ,'巨型蜈蚣':'Giant Centipede','巨型眼镜蛇':'Giant Cobra','疫病大鼠':'Plague Rat','巨型蝎子':'Giant Scorpion','巨型蜘蛛':'Giant Spider','巨型臭虫':'Giant Stinkbug','巨毒蜂':'Giant Venom Wasp','灰牛头人':'Ash Minotaur','绿飞虫':'Green Flier','绿腐虫':'Green Rotworm','地狱螃蟹':'Hell Crab','地狱领主':'Hell Lord','低级牛头人':'Lesser Minotaur','低等骷髅':'Lesser Skeleton','蜥蜴怪':'Lizard Fiend'
  ,'牛头队长':'Minotaur Captain','牛头火法师':'Minotaur Pyromancer','牛头斗士':'Minotaur Brawler','牛头冰法师':'Minotaur Cryomancer','牛头战士':'Minotaur Warrior','变异食人花':'Mutant Man-Eater','变异蛆':'Mutant Maggot','巨怪':'Ogre','巨怪首领':'Ogre Chieftain','诅咒傀儡':'Cursed Puppet','红恶魔':'Red Demon','红巨怪':'Red Ogre','骷髅兵':'Skeleton Soldier','骷髅射手':'Skeleton Archer','骷髅杀手':'Skeleton Slayer'
  ,'骷髅队长':'Skeleton Captain','骷髅守卫':'Skeleton Guard','骷髅领主':'Skeleton Lord','骷髅长枪兵':'Skeleton Lancer','骷髅战士':'Skeleton Warrior','蛛网射手':'Web Spitter','尖刺甲虫':'Spiked Beetle','高速蜘蛛':'Fleet Spider','狼人村民':'Werewolf Villager','狂化狼人':'Frenzied Werewolf','野狼':'Wolf','蚯蚓蛇':'Worm Serpent','雪怪':'Yeti','腐尸':'Rotting Corpse','疫尸':'Plague Corpse'
  ,'大地之母':'Earth Mother','地狱主虫':'Infernal Broodmaster','恶魔之王':'Demon King','亵渎巨树':'Desecrated Great Tree','炼狱魔王':'Infernal Overlord','梦魇魔蛇':'Nightmare Serpent','腐肉山峦':'Mountain of Carrion','真火龙':'Trueflame Dragon','蜘蛛之王':'Spider King','黑暗统治者':'Dark Sovereign'
  // Generated loot joins these translated roots with an English weapon name.
  ,'灰烬':'Ashen ','守墓':'Gravekeeper ','暮光':'Twilight ','流亡':'Exile '
};

// Room labels already have stable English archetype IDs. Reuse them so every
// procedurally selected chamber name follows the language toggle without a
// second hand-maintained list.
const humanize=(value:string)=>value.split('-').map(word=>word[0]?.toUpperCase()+word.slice(1)).join(' ');
for(const design of Object.values(THEME_DESIGNS)){
  for(const type of Object.keys(design.roomNames) as Array<keyof typeof design.roomNames>){
    const names=design.roomNames[type],archetypes=design.archetypes[type];
    names.forEach((name,index)=>{phrases[name]=humanize(archetypes[index%archetypes.length]);});
  }
  phrases[design.secretName]=humanize(design.secretArchetype);
  phrases[design.hazardName]=humanize(design.hazard);
}

const ordered=Object.entries(phrases).sort((a,b)=>b[0].length-a[0].length);
export function t(value:string):string{
  if(locale==='zh'||!value)return value;
  let translated=phrases[value]??value;
  if(translated===value)for(const[from,to]of ordered)translated=translated.replaceAll(from,to);
  // Generated affix names are assembled as “prefix 的 base · suffix”. Once the
  // translated components are Latin, remove only that joiner without touching
  // ordinary Chinese prose that may still need an explicit dictionary entry.
  translated=translated.replace(/([A-Za-z’]+)的(?=[A-Za-z])/g,'$1 ');
  return translated.replaceAll('。','.').replaceAll('；',';').replaceAll('，',',');
}

/** Translate generated UI after each render while preserving icons and values. */
const originalText=new WeakMap<Node,string>(),originalAttributes=new WeakMap<HTMLElement,Record<string,string>>();
export function localizeDom(root:HTMLElement):void{
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;
  while((node=walker.nextNode()))if(node.nodeValue?.trim()){
    const known=originalText.get(node),source=known??node.nodeValue;originalText.set(node,source);node.nodeValue=locale==='en'?t(source):source;
  }
  for(const element of root.querySelectorAll<HTMLElement>('[title],[aria-label],[placeholder]')){
    const stored=originalAttributes.get(element)??{};
    for(const attr of ['title','aria-label','placeholder']){const value=stored[attr]??element.getAttribute(attr);if(value){stored[attr]=value;element.setAttribute(attr,locale==='en'?t(value):value);}}
    originalAttributes.set(element,stored);
  }
}
